/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDatasetsRouteImport } from './routes/_authenticated/datasets'
import { Route as AuthenticatedFilterRouteImport } from './routes/_authenticated/filter'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedNotepadRouteImport } from './routes/_authenticated/notepad'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSavedFiltersRouteImport } from './routes/_authenticated/saved-filters'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDatasetsRoute = AuthenticatedDatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFilterRoute = AuthenticatedFilterRouteImport.update({
  id: '/filter',
  path: '/filter',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotepadRoute = AuthenticatedNotepadRouteImport.update({
  id: '/notepad',
  path: '/notepad',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSavedFiltersRoute =
  AuthenticatedSavedFiltersRouteImport.update({
    id: '/saved-filters',
    path: '/saved-filters',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/datasets': typeof AuthenticatedDatasetsRoute
  '/filter': typeof AuthenticatedFilterRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/import': typeof AuthenticatedImportRoute
  '/notepad': typeof AuthenticatedNotepadRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/saved-filters': typeof AuthenticatedSavedFiltersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/datasets': typeof AuthenticatedDatasetsRoute
  '/filter': typeof AuthenticatedFilterRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/import': typeof AuthenticatedImportRoute
  '/notepad': typeof AuthenticatedNotepadRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/saved-filters': typeof AuthenticatedSavedFiltersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/datasets': typeof AuthenticatedDatasetsRoute
  '/_authenticated/filter': typeof AuthenticatedFilterRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/notepad': typeof AuthenticatedNotepadRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/saved-filters': typeof AuthenticatedSavedFiltersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/datasets'
    | '/filter'
    | '/history'
    | '/import'
    | '/notepad'
    | '/profile'
    | '/saved-filters'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/datasets'
    | '/filter'
    | '/history'
    | '/import'
    | '/notepad'
    | '/profile'
    | '/saved-filters'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/datasets'
    | '/_authenticated/filter'
    | '/_authenticated/history'
    | '/_authenticated/import'
    | '/_authenticated/notepad'
    | '/_authenticated/profile'
    | '/_authenticated/saved-filters'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/datasets': {
      id: '/_authenticated/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof AuthenticatedDatasetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/filter': {
      id: '/_authenticated/filter'
      path: '/filter'
      fullPath: '/filter'
      preLoaderRoute: typeof AuthenticatedFilterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notepad': {
      id: '/_authenticated/notepad'
      path: '/notepad'
      fullPath: '/notepad'
      preLoaderRoute: typeof AuthenticatedNotepadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/saved-filters': {
      id: '/_authenticated/saved-filters'
      path: '/saved-filters'
      fullPath: '/saved-filters'
      preLoaderRoute: typeof AuthenticatedSavedFiltersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDatasetsRoute: typeof AuthenticatedDatasetsRoute
  AuthenticatedFilterRoute: typeof AuthenticatedFilterRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedNotepadRoute: typeof AuthenticatedNotepadRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSavedFiltersRoute: typeof AuthenticatedSavedFiltersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDatasetsRoute: AuthenticatedDatasetsRoute,
  AuthenticatedFilterRoute: AuthenticatedFilterRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedNotepadRoute: AuthenticatedNotepadRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSavedFiltersRoute: AuthenticatedSavedFiltersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
